/**
* Nombre: ConstantsEstafetaService
* Autor: Mauricio Rosales
* Descripcion: Clase contenedora de Constantes y Custom Labels, para las clases que se utilizan en la clase programada ScheduleBatchUpdateCasesEmboce
* --------------------------------------------------------------------------
* Versión       Fecha           Autor                   Descripción
* --------------------------------------------------------------------------
* 1.0           31/03/2023      Mauricio Rosales            Creación
* --------------------------------------------------------------------------
*/
public class ConstantsEstafetaService {    

    ///Class: EstafetaService
    public final static String ESTAFETA_ENDPOINT_TOKEN = System.Label.ESTAFETA_ENDPOINT_TOKEN;
    public final static String ESTAFETA_ENDPOINT_CUSTSHIPMENTTRACKING = System.Label.ESTAFETA_ENDPOINT_CUSTSHIPMENTTRACKING;
    public final static String ESTAFETA_SEARCHTYPE = System.Label.ESTAFETA_SEARCHTYPE;
    public final static String ESTAFETA_WAYBILLTYPE = System.Label.ESTAFETA_WAYBILLTYPE;
    public final static String ESTAFETA_FILTERTYPE = System.Label.ESTAFETA_FILTERTYPE;
    public final static String ESTAFETA_HISTORYTYPE = System.Label.ESTAFETA_HISTORYTYPE;
    
    public final static String HTTP_METHOD_POST = System.Label.HTTP_METHOD_POST;
    public final static String HTTP_GRANT_TYPE = System.Label.HTTP_GRANT_TYPE;
    public final static String HTTP_CLIENT_CREDENTIALS = System.Label.HTTP_CLIENT_CREDENTIALS;
    public final static String HTTP_SCOPE = System.Label.HTTP_SCOPE;
    public final static String HTTP_EXECUTE = System.Label.HTTP_EXECUTE;
    public final static String HTTP_CLIENT_ID = System.Label.HTTP_CLIENT_ID;
    public final static String HTTP_CLIENT_SECRET = System.Label.HTTP_CLIENT_SECRET;
    public final static String HTTP_CONTENT_TYPE = System.Label.HTTP_CONTENT_TYPE;
    public final static String HTTP_APP_URLENCODED = System.Label.HTTP_APP_URLENCODED;
    public final static String HTTP_ACCEPT = System.Label.HTTP_ACCEPT;
    public final static String HTTP_APP_JSON = System.Label.HTTP_APP_JSON;
    public final static String HTTP_APIKEY = System.Label.HTTP_APIKEY;
    public final static String HTTP_AUTHORIZATION = System.Label.HTTP_AUTHORIZATION;
    public final static String HTTP_BEARER = System.Label.HTTP_BEARER;
}